name: Build and Push

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Generate tag
        id: generate_tag
        run: echo "::set-output name=tag::$(echo ${GITHUB_SHA} | cut -c1-8)"

      - name: Build and push app container (latest)
        env:
          APP_CONTAINER_NAME: mshahidtaj/food-order-app
          TAG: latest
        run: |
          make build-food-order-app
          make push-food-order-app

      - name: Build and push app container (tag)
        env:
          APP_CONTAINER_NAME: mshahidtaj/food-order-app
          TAG: ${{ steps.generate_tag.outputs.tag }}
        run: |
          make build-food-order-app
          make push-food-order-app

      - name: Build and push UI container (latest)
        env:
          UI_CONTAINER_NAME: mshahidtaj/food-order-ui
          TAG: latest
        run: |
          make build-food-order-ui
          make push-food-order-ui

      - name: Build and push UI container (tag)
        env:
          UI_CONTAINER_NAME: mshahidtaj/food-order-ui
          TAG: ${{ steps.generate_tag.outputs.tag }}
        run: |
          make build-food-order-ui
          make push-food-order-ui
